"""Music scale finder package."""

from .finder import ScaleFinder, ScaleMatch
from .fingering import FingeringAnalyzer
from .melody_transcriber import MelodyEvent, MelodyTabResult, MelodyTranscriber, TabPosition
from .models import (
    AnalysisResults,
    ChordCandidate,
    AlternateFingering,
    DifficultyScore,
    Duration,
    ExportMetadata,
    FingerAssignment,
    FingeringAnalysis,
    IntervalInfo,
    NoteEvent,
    PlaybackEvent,
    PlaybackCursor,
    PlaybackMetadata,
    PlaybackStatus,
    PerformanceAnalysis,
    PositionSuggestion,
    PositionShift,
    PracticeAnalysis,
    ProjectState,
    QualityReport,
    ScaleAnalysis,
    StretchIssue,
    TabQualityIssue,
    Tempo,
    TimeSignature,
    Timeline,
    TimelineEvent,
    TimelineMarker,
)
from .playback import TimelineBuilder
from .session import MelodySession
from .theory import TheoryEngine

__all__ = [
    "AnalysisResults",
    "AlternateFingering",
    "ChordCandidate",
    "DifficultyScore",
    "Duration",
    "ExportMetadata",
    "FingerAssignment",
    "FingeringAnalyzer",
    "FingeringAnalysis",
    "IntervalInfo",
    "ScaleFinder",
    "ScaleMatch",
    "ScaleAnalysis",
    "MelodyEvent",
    "MelodyTabResult",
    "MelodyTranscriber",
    "NoteEvent",
    "PlaybackEvent",
    "PlaybackCursor",
    "PlaybackMetadata",
    "PlaybackStatus",
    "PerformanceAnalysis",
    "PositionSuggestion",
    "PositionShift",
    "PracticeAnalysis",
    "ProjectState",
    "QualityReport",
    "TabPosition",
    "StretchIssue",
    "TabQualityIssue",
    "Tempo",
    "TimeSignature",
    "Timeline",
    "TimelineBuilder",
    "TimelineEvent",
    "TimelineMarker",
    "MelodySession",
    "TheoryEngine",
]
